preload = /home/mau/Descargas/karly-jones-h6HPQv8myQw-unsplash.jpg
wallpaper = eDP-1,/home/mau/Descargas/karly-jones-h6HPQv8myQw-unsplash.jpg
wallpaper = HDMI-A-1,/home/mau/Descargas/karly-jones-h6HPQv8myQw-unsplash.jpg
