# Apps
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT CTRL, M, exit
bind = $mainMod, E, exec, dolphin
bind = $mainMod, R, exec, rofi -show drun
bind = $mainMod, F, fullscreen
bind = $mainMod, V, togglefloating
bind = $mainMod, P, pseudo

# Navegación
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod ALT, up, focusmonitor, HDMI-A-1
bind = $mainMod ALT, down, focusmonitor, eDP-1

# Mover ventanas
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# Redimensionar
binde = $mainMod CTRL, right, resizeactive, 50 0
binde = $mainMod CTRL, left, resizeactive, -50 0
binde = $mainMod CTRL, up, resizeactive, 0 -50
binde = $mainMod CTRL, down, resizeactive, 0 50

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod ALT, left, workspace, e-1
bind = $mainMod ALT, right, workspace, e+1

# Scratchpad
bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Screenshots
bind = , Print, exec, hyprshot -z -m region -o $shots
bind = SHIFT, Print, exec, hyprshot -z -m region --clipboard-only
bind = CTRL, Print, exec, hyprshot -m active -m output -o $shots
bind = ALT, Print, exec, hyprshot -m active -m window -o $shots

# Hardware
bind = , XF86MonBrightnessUp, exec, swayosd-client --brightness raise
bind = , XF86MonBrightnessDown, exec, swayosd-client --brightness lower
bind = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bind = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle

# Utilidades
bind = $mainMod SHIFT, R, exec, hyprctl reload
bind = SUPER, ESCAPE, exec, wlogout --protocol layer-shell
bind = SUPER, L, exec, hyprlock
bind = $mainMod, Space, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = $mainMod SHIFT, F, fullscreen, 1
bind = $mainMod, W, exec, ~/.config/hypr/scripts/wallpicker.sh
