general {
    border_size = 1
    col.active_border = $foreground
    col.inactive_border = $background
    gaps_in = 5
    gaps_out = 10
    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true
}

decoration {
    rounding = 2
    active_opacity = 1.0
    inactive_opacity = 0.85
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
    }
    shadow {
        enabled = false
    }
}
