-- Generated by nwg-displays on 2026-05-30 at 22:45:06. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1920@120.0",
    position = "1698x1080",
    scale = 2.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1440x0",
    scale = 1.0
})
