# Share picker
windowrule = float true, center true, opaque true, match:class hyprland-share-picker

# PiP
windowrule = float true, pin true, keep_aspect_ratio true, match:title .*Picture[- ]in[- ]Picture.*

# Blur en layers
layerrule = blur on, ignore_alpha 1, match:namespace waybar
layerrule = blur on, ignore_alpha 1, match:namespace rofi

# Blur en apps especificas
windowrule = opacity 0.92 0.85, match:class code
