$text_color = rgba(c4c5c2FF)
$text_dim = rgba(676e5aAA)
$entry_background_color = rgba(14190b99)
$entry_border_color = rgba(676e5a33)
$entry_color = rgba(c4c5c2FF)
$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$background_image = /home/mau/Pictures/wallpapers/TLOTR.jpg
