$text_color = rgba(d4cfc9FF)
$entry_background_color = rgba(0e0e0ecc)
$entry_border_color = rgba(a89f9655)
$entry_color = rgba(d4cfc9FF)
$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$background_image = /home/mau/Pictures/wallpapers/camille.jpg
