$text_color = rgba(c1c5c4FF)
$text_dim = rgba(596d66AA)
$entry_background_color = rgba(09171399)
$entry_border_color = rgba(596d6633)
$entry_color = rgba(c1c5c4FF)
$font_family = JetBrainsMono Nerd Font
$font_family_clock = JetBrainsMono Nerd Font
$background_image = /home/mau/Pictures/wallpapers/fuji.jpg
